### PR TITLE
fix: issue #87

### PR DESCRIPTION
**Pull request by christiangda**

### CODE REVIEW

**Comment by dalepaul-RL** [comment]
when will this be pushed, and what is the best way to upgrade my app with the new code? Will just a CF upgrade catch this, or do I have to change the source S3 arn?

**Comment by christiangda** [comment]
hi @dalepaul-RL , the best way to deploy a new version is always using the [AWS Serverless public repository - slashdevops/idp-scim-sync](https://serverlessrepo.aws.amazon.com/applications/us-east-1/889836709304/idp-scim-sync).  Just o there and deploy it in the same account you was using before for this.

**Comment by dalepaul-RL** [comment]
Thank you Christian. I also appreciate the quick resolution once the problem was identified.

**Comment by christiangda** [comment]
you're welcome @dalepaul-RL

**Pull request merged**
